services:
  - type: web
    name: voitans-discord-bot
    env: node
    plan: free
    buildCommand: cd bot && npm install
    startCommand: cd bot && node index.js
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: anthropic/claude-3.5-sonnet
      - key: OPENROUTER_HISTORY_LIMIT
        value: "30"
      - key: NODE_ENV
        value: production
      - key: BOT_PREFIX
        value: "!"
      - key: GUILD_ID
        sync: false
      - key: CLIENT_ID
        sync: false
